### ISSUE TITLE
leaves method doesn't work

### ISSUE THREAD

**Issue by mmiseyko** [Leadformance/ltree_hierarchy#10]
ModelName.leaves doesn't return any instances of model. But ModelName.roots returns good data.

**Comment by tomekw** [comment]
Hi @mmiseyko, sorry to hear that. Could you provide more info and steps to reproduce (ideally with example code) or even better: failing specs?

**Comment by tomekw** [comment]
@mmiseyko I think I've reproduced the issue, expect a fix soon!

**Comment by tomekw** [comment]
@mmiseyko fixed in `0.0.7`! :)

**Comment by mmiseyko** [comment]
@tomekw 
thank you :)
