### ISSUE TITLE
Split error for nil

### ISSUE THREAD

**Issue by carsonwright** [Leadformance/ltree_hierarchy#16]
I'm getting this error, but I'm not quite sure what I've done wrong or if its a bug in the gem.

NoMethodError: undefined method `split' for nil:NilClass
	from /home/carsonwright/.rvm/gems/ruby-2.1.2/gems/ltree_hierarchy-0.0.7/lib/ltree_hierarchy/hierarchy.rb:96:in `prevent_circular_paths'

**Comment by tomekw** [comment]
@carsonwright could you describe what you were doing then to help me reproduce this issue? :)

**Comment by carsonwright** [comment]
Yes sorry, um I was trying to add a child to a parent

I added a path column with ltree as its type and a parent_id with integer as its type and added an index to parent_id

And placed  
has_ltree_hierarchy
in the organization model

Then tried to run the following:
root = Organization.find(1)
Organization.find(2).update_attributes(parent: root)

**Comment by tomekw** [comment]
Thanks! I will take a look as soon as possible!

**Comment by carsonwright** [comment]
Thank you

**Comment by tomekw** [comment]
@carsonwright I wasn't able to reproduce the issue :(

Could you run:

`\d organizations`

and

`SELECT * FROM organizations WHERE id IN (1, 2)`

?

**Comment by carsonwright** [comment]
Column         |            Type             |                         Modifiers                          
------------------------+-----------------------------+------------------------------------------------------------
 id                     | integer                     | not null default nextval('organizations_id_seq'::regclass)
 parent_organization_id | integer                     | 
 created_at             | timestamp without time zone | 
 updated_at             | timestamp without time zone | 
 path                   | ltree                       | 
 parent_id              | integer                     | 
Indexes:
    "organizations_pkey" PRIMARY KEY, btree (id)
    "index_organizations_on_parent_id" btree (parent_id)
    "index_organizations_on_parent_organization_id" btree (parent_organization_id)

**Comment by carsonwright** [comment]
id | parent_organization_id |        created_at         |         updated_at         | path | parent_id 
----+------------------------+--------+----------+------+--------------+-------+------------------+-----------+
  1 |                    |  2015-08-07 20:39:02.792114 | 2015-08-21 06:21:50.638611 |      |          
  2 |                 1 |  2015-08-07 20:39:49.742189 | 2015-08-21 18:07:55.590456 |      |

**Comment by carsonwright** [comment]
Ok so I understand now I had data already created, and that data did not have its own id as the path so it was breaking everything

**Comment by carsonwright** [comment]
Thank you for your help

**Comment by tomekw** [comment]
Oh, it looks like so! I didn't have time to look at this. Glad it's all solved now!
